name: Build and deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Karavan VS Code extension (install dependencies)
        working-directory: ./karavan-vscode  
        run: yarn install 

      - name: Karavan VS Code extension (build)
        working-directory: ./karavan-vscode  
        run: yarn run package 